### PR TITLE
Make this fork synchron with the original

### PR DESCRIPTION
**Pull request by GitToTheHub**
Hi,

thanks for your great work, to make this plugin work again for Android. Your code quality is very good and worth to be merged in the original.

This PR is only, to synchronize your fork with the original, so that your fork is not behind something. The only really change is, that a `<br>` is removed in the readme-file. If you merge this, your fork is up-to-date with the original.

Regards,

Manuel

### CODE REVIEW

**Comment by dpalou** [comment]
Hi @GitToTheHub ,

I just saw that you included all our improvements in the original repository, thank you for that! We wanted our customizations to be part of the official repo, and [we opened a PR](https://github.com/katzer/cordova-plugin-local-notifications/pull/1781) with the first changes, but it was never integrated so we didn't send any further PRs, we just kept using our fork.

If you do a release of the official plugin and everything works properly, we can stop using our fork and use the official version instead. In those cases, what we do is just add a notice in our README saying that this plugin is deprecated and the official one should be used instead.

I'm saying this because it seems there are some conflicts in your PullRrequest, probably because of our changes in the plugin ID and versions. So instead of investing time on fixing that, I guess it's easier if we just add a deprecation notice in the README once we stop using our fork, and leave the rest of the code as it is right now.

Cheers,
Dani

**Comment by GitToTheHub** [comment]
Hi @dpalou,

sounds good what you wrote. We can make it like this. I'm rely thankful, that you published your changes on your repo. I will make a release of the orginal. I have just to fix a small thing.

Thank you again :)

Regards, Manuel

**Comment by GitToTheHub** [comment]
Hi, I made a release v1.0.0, but it's currently not published on NPM. I hope the original author will publish the release.

**Comment by GitToTheHub** [comment]
Hi the release is out on npm.

**Pull request closed without merging**
